version: 2

sources:
  - name: raw
    database: "{{ env_var('DB_NAME') }}"
    schema: public
    tables:
      - name: cleaned_messages
        columns:
          - name: message_id
            tests:
              - unique
              - not_null
          - name: channel
            tests:
              - not_null
          - name: date
            tests:
              - not_null

models:
  - name: stg_messages
    columns:
      - name: message_id
        tests:
          - unique
          - not_null
      - name: channel
        tests:
          - not_null
      - name: date
        tests:
          - not_null 